x-default: &default
  SMTP_HOST: 'smtp'
  SMTP_PORT: '1025'
  SMTP_PROTOCOL: 'standard'
  SMTP_USERNAME: ''
  SMTP_PASSWORD: ''
  APP_DEBUG: '1'

services:
  ingress:
    restart: unless-stopped
    environment:
      NGINX_FASTCGI_PASS: web:9000
    build:
      context: ./
      target: ingress
    ports:
      - 8888:80
    volumes:
      - files:/opt/drupal/web/sites/default/files
  web:
    build: ./
    restart: unless-stopped
    depends_on:
      smtp:
        condition: service_started
    environment:
      <<: *default
    env_file:
      - .env
    volumes:
      - data:/opt/drupal/data
      - files:/opt/drupal/web/sites/default/files
    develop:
      watch:
        - action: rebuild
          path: ./
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
volumes:
  files:
  data:
