version: '3'
services:
  web:
    build:
      context: ./
    ports:
      - 8888:80
    links:
      - smtp
    volumes:
      - ./:/var/www:cached
    command: 'sh -c "composer install -d /var/www && apache2-foreground"'
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
