version: '3'
services:
  web:
    image: davidbarratt/davidwbarratt
    env_file:
      - .env
  cron:
    image: davidbarratt/cron
    env_file:
      - .env
    links:
      - web
volumes:
  files:
  tmp:
