version: '3'
services:
  web:
    build:
      context: ./
    ports:
      - 8888:80
    links:
      - smtp
    volumes:
      - ./:/var/www:cached
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
