version: '3'
services:
  web:
    build:
      context: ./
    ports:
      - 8888:80
    links:
      - smtp
    volumes:
      - ./:/var/www:cached
    command: 'sh -c "composer install -d /var/www && apache2-foreground "'
    user: 'dev'
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      APP_DEBUG: ${APP_DEBUG:-1}
      SMTP_HOST: ${SMTP_HOST:-smtp}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_ENCRYPTION: ${SMTP_ENCRYPTION:-0}
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
