version: '3'
services:
  web:
    image: davidbarratt/davidwbarratt
    env_file:
      - .env
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_CACHE_DIR: /var/www/tmp/composer
  cron:
    image: davidbarratt/cron
    links:
      - web
volumes:
  files:
  tmp:
