version: '3'
services:
  web:
    build:
      context: ./
    user: "${DOCKER_UID}:${DOCKER_GID}"
    ports:
      - 8888:80
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    command: 'sh -c "composer install -d /var/www && apache2-foreground "'
    volumes:
      - ./:/var/www:cached
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
