version: '3'
services:
  web:
    restart: always
    networks:
      - default
      - ingress
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: davidwbarratt.com,origin.davidwbarratt.com,www.davidwbarratt.com
      LETSENCRYPT_HOST: davidwbarratt.com,origin.davidwbarratt.com,www.davidwbarratt.com
    volumes:
      - files:/var/www/html/sites/default/files
      - tmp:/var/www/tmp
  cron:
    restart: always
    env_file:
      - .env
networks:
  ingress:
    external:
      name: ingress
