version: '3'
services:
  web:
    image: davidbarratt/davidwbarratt
    environment:
      COMPOSER_MEMORY_LIMIT: -1
  cron:
    image: davidbarratt/cron
    links:
      - web
volumes:
  files:
  tmp:
