version: '3'

output: prefixed

dotenv:
  - .env

tasks:
  nginx:prepare:
    internal: true
    env:
      NGINX_PORT: 8888
      NGINX_FASTCGI_PASS: 'localhost:9000'
      NGINX_ROOT: web
    cmds:
      - mkdir -p tmp/nginx
      - mkdir -p etc/nginx/conf.d
      - envsubst '$NGINX_PORT $NGINX_FASTCGI_PASS $NGINX_ROOT' < ./etc/nginx/templates/default.conf.template > ./etc/nginx/conf.d/default.conf

  nginx:
    deps:
      - nginx:prepare
    internal: true
    cmd: nginx -c etc/nginx/nginx.conf -p $PWD

  php:prepare:
    internal: true
    cmd: mkdir -p tmp/php-fpm

  php:
    deps:
        - php:prepare
    internal: true
    env:
      APP_DEBUG: 'true'
    cmd: php-fpm8.4 --pid $PWD/tmp/php-fpm/php-fpm.pid  --force-stderr --fpm-config ./etc/php/php-fpm.conf

  drush:
    interactive: true
    cmd: composer exec drush {{.CLI_ARGS}}

  dev:
    deps:
      - nginx
      - php
