version: '3'

dotenv:
  - .env

tasks:
  dev:server:
    env:
      APP_DEBUG: 'true'
    internal: true
    dir: ./web
    cmd: php -S localhost:8888

  drush:
    cmd: composer exec drush {{.CLI_ARGS}}

  dev:
    deps:
      - dev:server
