# Schema for the configuration files of the CloudFlare module.
cloudflare_worker_purge.settings:
  type: config_object
  label: 'Cloudflare Worker Purge Settings'
  mapping:
    url:
      label: 'URL'
      type: uri
      translatable: false
