palette:
  top: '#658E97'
  bottom: '#658E97'
  bg: '#e8e8e8'
  sidebar: '#d2d2d2'
  sidebarborders: '#a3a3a3'
  footer: '#658E97'
  titleslogan: '#ffffff'
  text: '#000000'
  link: '#658E97'
logo: 'public://color/bartik-df3a1297/logo.svg'
stylesheets:
  - 'public://color/bartik-df3a1297/colors.css'
files:
  - 'public://color/bartik-df3a1297/logo.svg'
  - 'public://color/bartik-df3a1297/colors.css'
