_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  cloudflare: 0
  cloudflare_worker_purge: 0
  cloudflarepurger: 0
  comment: 0
  config: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dynamic_page_cache: 0
  editor: 0
  error_log: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  health_check: 0
  highlight_js: 0
  image: 0
  imagemagick: 0
  key: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  name: 0
  navigation: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  purge: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_ui: 0
  responsive_image: 0
  s3fs: 0
  smtp: 0
  sophron: 0
  sophron_guesser: 0
  sqlite: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  update: 0
  user: 0
  views_ui: 0
  http_cache_control: 1
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  claro: 0
  olivero: 0
profile: standard
