module:
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  cloudflare: 0
  cloudflarepurger: 0
  color: 0
  comment: 0
  config: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  http_cache_control: 0
  image: 0
  imagemagick: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  purge: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_queuer_url: 0
  purge_ui: 0
  quickedit: 0
  responsive_image: 0
  schema_article: 0
  schema_item_list: 0
  schema_metatag: 0
  schema_person: 0
  schema_web_page: 0
  sophron: 0
  sophron_guesser: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  olivero: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
