cache:
  http:
    s_maxage: 86400
    404_max_age: 0
    302_max_age: 0
    301_max_age: 0
    5xx_max_age: 0
    stale_while_revalidate: 3600
    stale_if_error: 3600
    vary: ''
  surrogate:
    maxage: 0
    nostore: null
_core:
  default_config_hash: 7J75jee6uT-qT16hDiNTHOtRFPgAz_ppCBdl7GTo-As
