_core:
  default_config_hash: 7J75jee6uT-qT16hDiNTHOtRFPgAz_ppCBdl7GTo-As
cache:
  http:
    s_maxage: 31536000
    404_max_age: 604800
    302_max_age: 0
    301_max_age: 604800
    5xx_max_age: 0
    stale_while_revalidate: 0
    stale_if_error: 0
    vary: ''
    mustrevalidate: 0
    nocache: 0
    nostore: 0
    cookieextra: null
  surrogate:
    maxage: 0
    nostore: false
