channels:
  -
    id: purgers
    grants:
      - 0
      - 1
      - 2
      - 3
      - 4
  -
    id: queue
    grants:
      - 0
      - 1
      - 2
      - 3
      - 4
  -
    id: diagnostics
    grants:
      - 0
      - 1
      - 2
      - 3
      - 4
  -
    id: purger_cloudflare_9a235f0ae1
    grants:
      - 0
      - 2
      - 3
