purgers:
  -
    instance_id: 9a235f0ae1
    plugin_id: cloudflare
    order_index: 2
processors:
  -
    plugin_id: drush_purge_queue_work
    status: true
  -
    plugin_id: drush_purge_invalidate
    status: false
  -
    plugin_id: purge_ui_block_processor
    status: true
  -
    plugin_id: lateruntime
    status: true
queue: database
