channels:
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_cloudflare_04e6e43d38
    grants:
      - 0
      - 2
      - 3
