purgers:
  -
    order_index: 2
    instance_id: 04e6e43d38
    plugin_id: cloudflare
queuers:
  -
    plugin_id: coretags
    status: false
  -
    plugin_id: urlpath
    status: true
  -
    plugin_id: purge_ui_block_queuer
    status: false
processors:
  -
    plugin_id: lateruntime
    status: true
  -
    plugin_id: purge_ui_block_processor
    status: false
