_core:
  default_config_hash: cgKAYNNfiRLK7JmjmyWUVlMGvWcSkPlL-k9a_gMFM_g
credentials_file: ''
bucket: davidwbarratt
region: us-east-1
use_cname: true
domain_root: none
use_customhost: true
hostname: 'https://2659099e440328a773821e7db5363a84.r2.cloudflarestorage.com'
domain: files.davidwbarratt.com
use_path_style_endpoint: false
disable_version_sync: true
cache_control_header: ''
encryption: ''
use_https: true
ignore_cache: false
read_only: false
disable_cert_verify: false
redirect_styles_ttl: 0
root_folder: ''
public_folder: s3fs-public
private_folder: s3fs-private
presigned_urls: ''
saveas: ''
torrents: ''
use_cssjs_host: false
cssjs_host: ''
use_credentials_cache: false
credentials_cache_dir: ''
keymodule:
  secret_key_name: ''
  access_key_name: ''
disable_shared_config_files: true
