_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: da699117-cf7c-4e06-b82d-86a918e13953
name: 'david w barratt'
mail: site@davidwbarratt.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
