name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v5
        id: meta-web
        with:
          images: ghcr.io/${{ github.repository }}/web
          tags: |
            type=sha
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/metadata-action@v5
        id: meta-ingress
        with:
          images: ghcr.io/${{ github.repository }}/ingress
          tags: |
            type=sha
      - uses: docker/build-push-action@v5
        with:
          push: true
          target: ingress
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-ingress.outputs.tags }}
          labels: ${{ steps.meta-ingress.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

